// Package adr reads the decision records under docs/site/adr and renders their index.
//
// The shape a record must have is in CONTRIBUTING.md, under Writing a decision
// record. tools/adr validates and indexes them, and governance tests hold the
// repository to them.
package adr

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

// FrontMatter opens every record, so the docs search ranks records below pages.
const FrontMatter = "---\nsearch:\n  boost: 0.3\n---\n\n"

// IndexName is the generated index, which is not a record.
const IndexName = "index.md"

const indexHeader = `---
# Generated by ` + "`task docs:adr-index`" + ` from the records in this directory. Do not edit.
---

# Decision Records

How this project is built and worked on, one rule to a record. Each record says what
holds and why, and the alternatives it turned down.

`

var (
	fileName       = regexp.MustCompile(`^(\d{3})-([a-z0-9]+(?:-[a-z0-9]+)*)\.md$`)
	titleLine      = regexp.MustCompile(`^# ADR-(\d{3}): (\S.*)$`)
	notChosenEntry = regexp.MustCompile(`^- \*\*[^*]+\*\*: \S`)
)

// Record is one decision record.
type Record struct {
	Number int
	Title  string
	File   string
}

// Label is how a record is named elsewhere: ADR-007.
func (r Record) Label() string { return fmt.Sprintf("ADR-%03d", r.Number) }

// Parse reads one record and reports everything wrong with its shape at once.
func Parse(path string) (Record, error) {
	name := filepath.Base(path)
	match := fileName.FindStringSubmatch(name)
	if match == nil {
		return Record{}, fmt.Errorf("%s: the name must be NNN-slug.md, in lower case", name)
	}
	raw, err := os.ReadFile(path) //nolint:gosec // a path under the records directory
	if err != nil {
		return Record{}, err
	}
	text := string(raw)
	var problems []string
	if strings.Contains(text, "\r") {
		problems = append(problems, "contains a carriage return; records are LF")
	}
	if !strings.HasPrefix(text, FrontMatter) {
		problems = append(problems, "must open with the search front matter the other records carry")
	}
	lines := strings.Split(strings.TrimPrefix(text, FrontMatter), "\n")
	title := titleLine.FindStringSubmatch(lines[0])
	if title == nil {
		problems = append(problems, "the first line after the front matter must be # ADR-NNN: Title")
		return Record{}, fmt.Errorf("%s: %s", name, strings.Join(problems, "; "))
	}
	if title[1] != match[1] {
		problems = append(problems, fmt.Sprintf("titled ADR-%s in a file numbered %s", title[1], match[1]))
	}

	prose, section := 0, ""
	for _, line := range lines[1:] {
		switch {
		case strings.HasPrefix(line, "#"):
			if line != "## Not chosen" {
				problems = append(problems, fmt.Sprintf("has a heading other than '## Not chosen': %q", line))
			}
			section = line
		case strings.TrimSpace(line) == "":
		case section == "## Not chosen" && !notChosenEntry.MatchString(line):
			problems = append(problems, fmt.Sprintf("a Not chosen entry must read '- **Alternative**: why not': %q", line))
		case section == "":
			prose++
		}
	}
	if prose == 0 {
		problems = append(problems, "states no rule")
	}
	if !strings.HasSuffix(text, "\n") || strings.HasSuffix(text, "\n\n") {
		problems = append(problems, "must end with exactly one newline")
	}
	if len(problems) > 0 {
		return Record{}, fmt.Errorf("%s: %s", name, strings.Join(problems, "; "))
	}
	number, _ := strconv.Atoi(match[1])
	return Record{Number: number, Title: title[2], File: name}, nil
}

// LoadAll reads every record in dir, in number order, and fails on any record
// that does not parse and on two that share a number.
func LoadAll(dir string) ([]Record, error) {
	paths, err := filepath.Glob(filepath.Join(dir, "*.md"))
	if err != nil {
		return nil, err
	}
	var records []Record
	var problems []error
	seen := map[int]string{}
	for _, path := range paths {
		if filepath.Base(path) == IndexName {
			continue
		}
		record, err := Parse(path)
		if err != nil {
			problems = append(problems, err)
			continue
		}
		if other, ok := seen[record.Number]; ok {
			problems = append(problems, fmt.Errorf("%s and %s share %s", record.File, other, record.Label()))
			continue
		}
		seen[record.Number] = record.File
		records = append(records, record)
	}
	if len(problems) > 0 {
		return nil, errors.Join(problems...)
	}
	sort.Slice(records, func(i, j int) bool { return records[i].Number < records[j].Number })
	return records, nil
}

// RenderIndex is the index the records generate.
func RenderIndex(records []Record) string {
	var b strings.Builder
	b.WriteString(indexHeader)
	for _, r := range records {
		fmt.Fprintf(&b, "- [%s: %s](%s)\n", r.Label(), r.Title, r.File)
	}
	return b.String()
}
